# Generated by Django 5.1.4 on 2024-12-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provider',
            new_name='Seller',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='provider',
            new_name='seller',
        ),
    ]
