# Generated by Django 5.1.4 on 2024-12-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_seller_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='product_price',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
